const danhSachHoa = [
    { id: 1,
     name: "Trà Đào Cam Sả",
     price: 35000, 
     category: "Trà",
     img: "./btnhom-anh/tra-trai-cay/tra-dao-cam-xa.jpg",
    description: "Thức uống giải nhiệt cực đỉnh với miếng đào giòn tan và hương sả thơm nồng.",
     ingredients: "Trà túi lọc, đào ngâm, cam tươi, sả cây, mật ong." },
   
     { id: 2,
     name: "Matcha Đậu Đỏ", 
     price: 50000, 
     category: "Trà sữa", 
     img: "./btnhom-anh/matcha/ts-matcha-dau-do.jpg",
     description:" Sự kết hợp giữa matcha và bột trà xanh Nhật Bản",
    ingredients:"Matcha Nhật Bản , Sữa tách béo , Đường , Creamer , Đậu đỏ , Nước tinh khiết ."},
    
    { id: 3, 
    name: "Khô Gà Lá Chanh",
    price: 30000,
     category: "Ăn vặt",
     img: "./btnhom-anh/an-vat/kho-ga-la-chanh.jpg",
     description:"Món ăn vặt yêu thích của giới trẻ với sự kết hợp độc đáo của khô gà và lá chanh",
    ingredients:"Thịt gà, Lá chanh, Tỏi băm, Ớt tươi và ớt bột, nước mắm, đường, tiêu, ngũ vị hương, dầu điều và bột tỏi, Sả."},
    
    { id: 4,
     name: "Bánh Tráng Cuộn",
     price: 25000,
     category: "Ăn vặt", 
     img: "./btnhom-anh/an-vat/Banh-trang-cuon.jpg",
     description:"Bánh tráng cuộn là món ăn vặt quen thuộc, đặc biệt với học sinh  sinh viên vì gọn, dễ ăn và đậm vị 🌯",
    ingredients:"Bánh tráng, Xoài xanh bào sợi, Rau răm, dưa leo , Trứng cút luộc, Khô bò hoặc khô mực xé sợi, Tép khô, Đậu phộng rang, Hành phi, Sa tế, Nước mắm hoặc nước sốt me, Muối tôm / muối ớt , Đường, Tắc (quất) hoặc chanh"},
    
    { id: 5,
     name: "Trà Sữa Trân Châu Đường Đen",
    price: 38000, 
    category: "Trà sữa", 
    img: "./btnhom-anh/tra-sua/Sua-tuoi-tran-chau-duong-den.jpg",
    description:"Trà sữa trân châu đường đen là một trong những món đồ uống “gây nghiện” nhất với giới trẻ vì vị ngọt thơm của đường đen hòa cùng sữa béo và trân châu dẻo dai 🧋",
    ingredients:"Trà đen hoặc trà ô long, Sữa tươi hoặc bột sữa/kem béo, Đường hoặc syrup, Trân châu đường đen , Bột năng/bột sắn ,Đường đen."},
    
    { id: 6,
     name: "Bánh Tráng Trộn",
     price: 30000,
    category: "Ăn vặt", 
    img: "./btnhom-anh/an-vat/banh-trang-tron.jpg",
    description:"Bánh tráng trộn là một món ăn vặt “quốc dân” của học sinh ,sinh viên Việt Nam, nổi tiếng vì vị chua cay mặn ngọt trộn lẫn cực đã miệng 😋",
    ingredients:"Bánh tráng, Xoài xanh bào sợi, Rau răm, dưa leo , Trứng cút luộc, Khô bò hoặc khô mực xé sợi, Tép khô, Đậu phộng rang, Hành phi, Sa tế, Nước mắm hoặc nước sốt me, Muối tôm / muối ớt , Đường, Tắc (quất) hoặc chanh"},
    
    { id: 7,
     name: "Hot Dog", 
     price: 75000,
     category: "Ăn vặt",
     img: "./btnhom-anh/an-vat/hot-dog.jpeg",
     description:"Hot dog là món ăn nhanh nổi tiếng trên thế giới, đặc biệt phổ biến ở Mỹ 🌭",
    ingredients:"Bánh mì hot dog (dài, có rãnh ở giữa), Xúc xích,Tương cà, Mù tạt vàng, Mayonnaise, Dưa leo muối / dưa chua, Hành tây sống hoặc hành phi, Bắp cải trộn, Phô mai (tùy kiểu)"},
    
    { id: 8,
     name: "Trứng cút chiên",
     price: 30000,
     category: "Ăn vặt", 
     img: "./btnhom-anh/an-vat/trung-cuc-chien.jpg",
     description:"Trứng cút chiên là món ăn vặt quen thuộc, nhỏ xíu mà “có võ” vì béo, thơm và dễ ăn 🥚",
    ingredients:"Trứng cút tươi, Xúc xích cắt lát, Khô bò xé, Chà bông, Hành lá, Hành phi, Đậu phộng rang, Tương ớt,Tương cà, Mayonnaise, Nước tương, Muối tiêu hoặc muối ớt"},
    
    { id: 9, 
    name: "Xúc xích phô mai", 
    price: 35000, category: "Ăn vặt",
    img: "./btnhom-anh/an-vat/xuc-xich-pho-mai.jpg",
     description:"Xúc xích phô mai là món ăn vặt siêu “đã miệng” vì cắn một cái là phô mai chảy ra béo ngậy 🧀🌭",
    ingredients:"Hần xúc xích, Thịt xay Mỡ heo, muối, tiêu, đường, tỏi, Phô mai mozzarella hoặc Phô mai chedda"},
    

    { id: 10,
     name: "Xúc Xích Chiên",
     price: 30000,
     category: "Ăn vặt",
     img: "./btnhom-anh/an-vat/xuc-xich-ran-1.jpg",
     description:"Xúc xích chiên là món ăn vặt cực quen, thơm nức, béo nhẹ và ăn là dễ ghiền 🌭✨",
    ingredients:"Xúc xích, Dầu ăn, Tương cà, Tương ớt Mayonnaise, Dưa leo hoặc đồ chua"},
    
    { id: 11,
     name: "Khoai Tây Nghiền",
     price: 40000,
     category: "Ăn vặt", 
     img: "./btnhom-anh/an-vat/khoai-tay-nghien.jpg",
    description:"Khoai tây nghiền là món ăn mềm mịn, béo nhẹ và rất dễ ăn — thường xuất hiện trong các bữa ăn kiểu Âu hoặc ăn kèm đồ chiên, nướng 🥔✨",
    ingredients:"Khoai tây, Bơ, kem tươi, Muối, Tiêu, tỏi băm xào bơ "},
    
    { id: 12, 
    name: "Bánh Tráng Nướng",
     price: 40000, 
     category: "Ăn vặt", 
     img: "./btnhom-anh/an-vat/banh-trang-nuong.jpg",
     description:"Bánh tráng nướng được mệnh danh là “pizza Việt Nam” vì vừa giòn vừa đầy topping hấp dẫn 🔥🍕",
    ingredients:"Bánh tráng mỏng, Trứng gà hoặc trứng cút, Xúc xích cắt lát, Khô bò / khô gà, Chà bông, Tép khô, Hành lá, Phô mai bào, Mayonnaise, Tương ớt, Sa tế, Muối tiêu, Bơ"},
    
    { id: 13, 
    name: "Combo xiên bẩn", 
    price: 120000, 
    category: "Ăn vặt", 
    img: "./btnhom-anh/an-vat/anh-an-vat.jpg",
    description:"Combo “xiên bẩn” là cách gọi vui của học sinh, sinh viên cho các món xiên que chiên/nướng bán ở vỉa hè 🍢😆 (tên nghe ghê vậy thôi chứ thực ra là đồ ăn vặt siêu hấp dẫn)",
    ingredients:"Cá viên, Bò viên, Tôm viên, Mực viên, Phô mai que, Thanh cua, Xúc xích, Ba rọi cuộn, Gà viên chiên, Hồ lô, Há cảo chiên, Hoành thánh chiên, Đậu hũ cá, Bánh bao chiên mini"},
    
    { id: 14,
     name: "Matcha Latte",
     price: 35000, 
     category: "Trà sữa",
     img: "./btnhom-anh/matcha/Matcha-Latte.jpg",
     description:"Matcha latte là thức uống thơm dịu, béo nhẹ và có màu xanh rất “chill”, được nhiều bạn trẻ yêu thích 🍵💚",
    ingredients:"Bột matcha, Sữa tươi hoặc Sữa hạt (hạnh nhân, yến mạch…), Đường, Mật ong, Syrup vanilla"},
    
    { id: 15,
    name: "Matcha Dâu",
     price: 50000, 
     category: "Trà sữa", 
     img: "./btnhom-anh/matcha/matcha-dau.jpg",
    description:"Matcha dâu là món nước nhìn là mê ngay vì 2 tầng màu xanh – đỏ cực bắt mắt, vị thì vừa thanh vừa trái cây 🍓🍵",
    ingredients:"Bột matcha, Dâu tây tươi xay hoặc mứt/syrup dâu, Đường hoặc mật ong (tùy độ ngọt của dâu), Sữa tươi hoặc Sữa hạt (yến mạch, hạnh nhân…), Đá viên (nếu uống lạnh)"},
    
    { id: 16,
     name: "Trà Sữa Ô Long",
      price: 50000, 
      category: "Trà sữa",
       img: "./btnhom-anh/tra-sua/tra-sua-o-long.jpg",
    description:"Trà sữa ô long là lựa chọn cho những ai thích vị trà rõ, thơm mà không bị ngọt gắt 🧋🍃",
    ingredients:"Trà ô long, Sữa tươi hoặc Bột sữa/kem béo, Đường, Syrup đường, Mật ong"},
    
    { id: 17,
     name: "Trà Sữa Thái Xanh",
     price: 40000,
    category: "Trà sữa", 
    img: "./btnhom-anh/tra-sua/thai-xanh.jpg",
    description:"Trà sữa Thái xanh là món nước nổi bật với màu xanh lá sáng và hương vị thơm béo, ngọt dịu rất dễ uống 🧋",
    ingredients:"Trà Thái xanh, Sữa đặc, Sữa tươi hoặc sữa béo, Đường, Sữa đặc"},

    { id: 18,
     name: "Trà Sữa Socola",
     price: 40000, 
     category: "Trà sữa",
     img: "./btnhom-anh/tra-sua/tra-sua-scl.jpg",
    description:"Trà sữa socola là sự kết hợp giữa vị trà dịu nhẹ và socola ngọt béo, tạo thành món uống vừa quen vừa lạ 🍫🧋",
    ingredients:"Trà đen hoặc trà ô long, Sữa tươi hoặc Bột sữa/kem béo, Bột cacao hoặc Syrup socola, Đường, Sữa đặc, Syrup đường" },
    
    { id: 19, 
    name: "Trà Chanh Dây Xoài", 
    price: 45000,
    category: "Trà",
    img: "./btnhom-anh/tra-trai-cay/chanh-day-xoai.jpg",
    description:"Trà chanh dây xoài là phiên bản trái cây “nâng cấp” của trà chanh dây, có vị chua thanh hòa cùng ngọt thơm của xoài — uống là thấy mát liền 🥭🍹",
    ingredients:"Trà đen hoặc trà lài, Nước cốt chanh dây tươi hoặc syrup chanh dây, Xoài chín xay nhuyễn hoặc Syrup xoài, Đường, Mật ong"},  
    
    { id: 20,
     name: "Hồng Trà Bí Đao", 
     price: 40000, 
     category: "Trà",
      img: "./btnhom-anh/tra-trai-cay/hong-tra-bi-dao.jpg",
     description:"Hồng trà bí đao là thức uống có vị ngọt thanh tự nhiên, mùi thơm nhẹ và rất dễ uống, đặc biệt hợp khi uống lạnh 🧊🍵",
    ingredients:"Hồng trà, Nước bí đao nấu (bí đao + đường phèn, đôi khi thêm la hán quả hoặc lá dứa cho thơm), đường  tắc (quất) "},
    
    { id: 21,
     name: "Trà Atiso", 
     price: 50000, 
     category: "Trà",
      img: "./btnhom-anh/tra-trai-cay/tra-atiso.jpg",
      description:"Trà atiso là thức uống thảo mộc có vị thanh mát, hơi ngọt nhẹ tự nhiên, thường được uống để giải khát và thư giãn 🌺",
    ingredients:"Atiso đỏ, Đường phèn, Mật ong"},

    { id: 22,
     name: "Trà Chanh Kiwi",
      price: 55000, 
      category: "Trà",
       img: "./btnhom-anh/tra-trai-cay/tra-chanh-1.jpeg",
    description:"Trà chanh kiwi là thức uống trái cây tươi mát, có vị chua thanh pha chút ngọt dịu, rất hợp để giải khát ngày nóng 🥝🍋🧊",
    ingredients:"Trà đen hoặc trà lài, Nước cốt chanh, Kiwi tươi xay hoặc dầm hoặc Syrup kiwi, Đường, Mật ong "},
    
    { id: 23,
    name: "Trà Chanh",
     price: 35000, 
     category: "Trà",
      img: "./btnhom-anh/tra-trai-cay/tra-chanh-2.jpg",
    description:"Trà chanh là thức uống đơn giản mà “quốc dân”, nổi tiếng với vị chua ngọt mát lạnh, dễ uống và cực đã khát 🍋🧊",
    ingredients:"Trà đen hoặc trà lài, Nước cốt chanh tươi, lát chanh, Đường, Mật ong" },

    { id: 24,
     name: "Trà Đào Xoài", 
     price: 40000,
     category: "Trà",
     img: "./btnhom-anh/tra-trai-cay/tra-dao-xoai.jpg",
    description:"Trà đào xoài là món nước trái cây cực “hợp vibe mùa hè” với vị ngọt thơm của xoài hòa cùng đào và nền trà thanh mát 🍑🥭🧊",
    ingredients:"Trà đen hoặc trà lài, Đào ngâm lát hoặc Syrup đào, Xoài chín xay nhuyễn hoặc Syrup xoài, Nước ngâm đào, Đường hoặc mật ong"},
    
    { id: 25,
      name: "Trà Chanh Dây", 
      price: 35000, 
      category: "Trà",
      img: "./btnhom-anh/tra-trai-cay/tra-chanh-day.jpg",
     description:"Trà chanh dây là món nước chua ngọt thanh mát, thơm mùi trái cây và rất dễ uống, đặc biệt hợp khi uống lạnh 🧊🍹",
    ingredients:"Trà đen hoặc trà lài, Nước cốt chanh dây tươi hoặc Syrup chanh dây, Đường, Mật ong"},
    
    { id: 26,
     name: "Trà Đào ",
      price: 35000, 
      category: "Trà",
       img: "./btnhom-anh/tra-trai-cay/tra-dao.jpg",
     description:"Trà đào là thức uống trái cây rất được yêu thích vì vị ngọt thơm dịu nhẹ, dễ uống và mát lạnh 🍑🧊",
    ingredients:"Trà đen hoặc trà lài, Đào ngâm lát hoặc Syrup đào, Nước ngâm đào, Đường hoặc mật ong"},

    { id: 27,
     name: "Trà Hoa Cúc",
     price: 40000,
    category: "Trà",
    img: "./btnhom-anh/tra-trai-cay/tra-hoa-cuc.jpg",
    description:"Trà hoa cúc là thức uống thảo mộc nhẹ nhàng, có mùi thơm dịu và vị thanh mát, thường được uống để thư giãn 🌼",
    ingredients:"Hoa cúc khô, Đường phèn, Mật ong, Kỷ tử, Táo đỏ, Lá dứa"},

    { id: 28,
     name: "Trà Hoa Qué",
     price: 60000, 
     category: "Trà", 
     img: "./btnhom-anh/tra-trai-cay/tra-hoa-quế.jpg",
     description:"Trà hoa quế (osmanthus tea) là loại trà có hương thơm ngọt dịu như mật hoa, vị thanh nhẹ và rất dễ uống 🌼",
    ingredients:"Hoa quế khô (osmanthus), Trà xanh, Trà ô long Hoặc chỉ dùng hoa quế thuần không trà, Mật ong, Đường phèn, Kỷ tử, Táo đỏ, Lê lát mỏng"},
    
    { id: 30,
     name: "Trà Mật Ong",
     price: 50000, 
     category: "Trà",
     img: "./btnhom-anh/tra-trai-cay/tra-mat-ong.jpg",
    description:"Trà mật ong là thức uống đơn giản nhưng rất được yêu thích nhờ vị ngọt dịu tự nhiên và hương thơm nhẹ nhàng 🍯",
    ingredients:"Trà đen, hoặc trà xanh, Mật ong nguyên chất "},

    { id: 31,
     name: "Trà Lài",
     price: 40000, 
     category: "Trà",
     img: "./btnhom-anh/tra-trai-cay/tra-lai.jpg",
     description:"Trà lài (trà nhài) là loại trà có hương hoa thơm dịu, vị thanh nhẹ, rất dễ uống và hợp để giải khát hằng ngày 🌼",
     ingredients:"Trà xanh hoặc trà ô long đã được ướp với hoa nhài, Đường, Mật ong"},

    { id: 32,
     name: "Trà Quế ",
     price: 60000, 
     category: "Trà",
      img: "./btnhom-anh/tra-trai-cay/tra-que.jpg",
     description:"Trà quế là thức uống có mùi thơm ấm nồng đặc trưng, vị dịu nhẹ và thường được uống khi muốn cảm giác ấm áp, dễ chịu ☕🌿",
     ingredients:"Thanh quế khô hoặc Bột quế, Mật ong, Đường phèn"},

    { id: 33,
     name: "Trà Tắt", 
     price: 30000,
      category: "Trà",
       img: "./btnhom-anh/tra-trai-cay/tra-tac.jpeg",
     description:"Trà tắc là thức uống chua ngọt mát lạnh, thơm mùi vỏ tắc đặc trưng và cực kỳ giải khát 🍊🧊",
     ingredients:"Trà đen hoặc trà lài, Nước cốt tắc tươi, Vỏ tắc thái sợi mỏng, Đường / Mật ong "},
    
     { id: 34,
     name: "Trà Vải Thiều",
      price: 55000, 
      category: "Trà",
       img: "./btnhom-anh/tra-trai-cay/tra-vai-thieu.jpg",
    description:"Trà vải thiều là thức uống trái cây rất được yêu thích vì vị ngọt thơm đặc trưng của vải hòa cùng nền trà thanh mát 🍇🧊🍵",
     ingredients:"Trà đen hoặc trà lài, Vải thiều tươi bóc vỏ bỏ hạt hoặc Vải ngâm đóng hộp hoặc Syrup vải, Nước ngâm vải, Đường hoặc mật ong nếu cần thêm ngọt" },
    
     { id: 35,
    name: "Trà Việt Quất", 
    price: 55000,
     category: "Trà",
      img: "./btnhom-anh/tra-trai-cay/tra-viet-quat.jpg",
     description:"Trà việt quất là thức uống trái cây có vị chua ngọt dịu, màu tím đỏ bắt mắt và rất dễ uống 🫐🧊🍵",
     ingredients:"Trà đen hoặc trà lài ,Việt quất tươi dầm hoặc xay, Syrup việt quất, Đường / Mật ong "},
   
     { id: 36,
     name: "Trà Xanh", 
     price: 45000, 
     category: "Trà",
     img: "./btnhom-anh/tra-trai-cay/tra-xanh.jpg",
     description:"Trà xanh là thức uống quen thuộc có vị thanh, hơi chát nhẹ và hương thơm tự nhiên của lá trà 🍃🍵",
     ingredients:"Lá trà xanh khô, Trà xanh túi lọc, Đường hoặc mật ong nếu thích ngọt, Chanh để tạo trà xanh chanh, Bạc hà để tăng cảm giác mát"},
    
     { id: 37,
     name: "Trà Xoài", 
     price: 45000,
      category: "Trà", 
      img: "./btnhom-anh/tra-trai-cay/tra-xoai.jpg",
    description:"Trà xoài là thức uống trái cây có vị ngọt thơm đặc trưng của xoài hòa cùng nền trà thanh mát, rất hợp uống lạnh 🥭🧊🍵",
     ingredients:"Trà đen hoặc trà lài, Xoài chín xay nhuyễn hoặc Syrup xoài, Đường / Mật ong" },
    
     { id: 38,
     name: "Trà Dâu",
      price: 55000, 
      category: "Trà",
       img: "./btnhom-anh/tra-trai-cay/tra-dau.jpg",
     description:"Trà dâu là thức uống trái cây có vị chua ngọt dịu, thơm mùi dâu tây và màu đỏ hồng rất bắt mắt 🍓🧊🍵",
     ingredients:"Trà đen hoặc trà lài, Dâu tây tươi dầm/xay hoặc Syrup dâu Đường / Mật ong"},

    { id: 39,
     name: "Trà Cam Táo", 
     price: 55000, 
     category: "Trà", 
     img: "./btnhom-anh/tra-trai-cay/tra-cam-tao.jpg",
     description:"Trà cam táo là thức uống trái cây tươi mát với vị chua ngọt hài hòa và hương thơm tự nhiên, rất hợp để giải khát 🧊🍊🍎🍵",
     ingredients:"Trà đen hoặc trà lài, Nước cam tươi vắt, lát cam để tăng mùi thơm, Táo tươi ép hoặc xay lọc hoặc Syrup táo, Đường, Mật ong (tăng hương thơm)"},
    
     { id: 40,
     name: "Trân Châu Đen", 
     price: 5000, 
     category: "Topping",
      img: "./btnhom-anh/topping/tran-chau-den.jpg" },
    
     { id: 41,
     name: "Thạch Trái Cây",
    price: 7000,
    category: "Topping", 
    img: "./btnhom-anh/topping/thach-trai-cay-tra-cay.jpg" },

    { id: 42, 
    name: "Kem Cheese",
     price: 10000, 
     category: "Topping",
      img: "./btnhom-anh/topping/kem-chess.jpg" },

    { id: 43,
     name: "Bánh plan",
      price: 10000,
     category: "Topping",
     img: "./btnhom-anh/topping/banh-plan.jpg" },

    { id: 44,
      name: "Hạt Chia", 
      price: 5000,
       category: "Topping", 
       img: "./btnhom-anh/topping/hat-chia.jpg" },

    { id: 45,
     name: "Hạt Nổ Thủy Tinh",
     price: 10000, category: "Topping", 
     img: "./btnhom-anh/topping/hat-no-thuy-tinh.jpg" },

    { id: 46, 
    name: "Khúc Bạch Chân Mèo",
     price: 15000, 
     category: "Topping",
      img: "./btnhom-anh/topping/khuc-bach-chan-meo.jpg" },

    { id: 47,
     name: "Khúc Bạch",
     price: 10000,
     category: "Topping",
     img: "./btnhom-anh/topping/khuc-bach.jpg" },
    
    { id: 48,
     name: "Thạch Dừa",
     price: 5000, 
     category: "Topping",
     img: "./btnhom-anh/topping/thach-dua.jpg" },

    { id: 49,
     name: "Thạch Sương Sáo",
      price: 5000,
       category: "Topping", 
       img: "./btnhom-anh/topping/thach-suong-sao.jpg" },

    { id: 50,
     name: "Trân Châu Hoàng Kim",
      price: 7000,
     category: "Topping", 
     img: "./btnhom-anh/topping/tran-chau-hoang-kim.jpg" },

    { id: 51, 
    name: "Trân Châu Khoai Môn",
     price: 7000,
      category: "Topping",
       img: "./btnhom-anh/topping/tran-chau-khoai-mon.jpg" },

    { id: 52,
     name: "Trân Châu Trắng", 
     price: 7000, 
     category: "Topping",
      img: "./btnhom-anh/topping/tran-chau-trang.jpg" },
];