const danhSachHoa = [
   { id: 1, name: "Trà Đào Cam Sả", price: 35000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-dao-cam-xa.jpg" },
    { id: 2, name: "Matcha Đậu Đỏ", price: 50000, category: "Trà sữa", img: "./btnhom-anh/matcha/ts-matcha-dau-do.jpg" },
    { id: 3, name: "Khô Gà Lá Chanh", price: 30000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/kho-ga-la-chanh.jpg" },
    { id: 4, name: "Bánh Tráng Cuộn", price: 25000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/Banh-trang-cuon.jpg" },
    { id: 5, name: "Trà Sữa Trân Châu Đường Đen", price: 38000, category: "Trà sữa", img: "./btnhom-anh/tra-sua/Sua-tuoi-tran-chau-duong-den.jpg" },
    { id: 6, name: "Bánh Tráng Trộn", price: 30000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/banh-trang-tron.jpg" },
    { id: 7, name: "Hot Dog", price: 75000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/hot-dog.jpeg" },
    { id: 8, name: "Trứng cút chiên", price: 30000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/trung-cuc-chien.jpg" },
    { id: 9, name: "Xúc xích phô mai", price: 35000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/xuc-xich-pho-mai.jpg" },
    { id: 10, name: "Xúc Xích Chiên", price: 30000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/xuc-xich-ran-1.jpg" },
    { id: 11, name: "Khoai Tây Nghiền", price: 40000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/khoai-tay-nghien.jpg" },
    { id: 12, name: "Bánh Tráng Nướng", price: 40000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/banh-trang-nuong.jpg" },
    { id: 13, name: "Combo xiên bẩn", price: 120000, category: "Ăn vặt", img: "./btnhom-anh/an-vat/anh-an-vat.jpg" },
    { id: 14, name: "Matcha Latte", price: 35000, category: "Trà sữa", img: "./btnhom-anh/matcha/Matcha-Latte.jpg" },
    { id: 15, name: "Matcha Đậu Đỏ", price: 50000, category: "Trà sữa", img: "./btnhom-anh/matcha/ts-matcha-dau-do.jpg" },
    { id: 16, name: "Trà Sữa Ô Long", price: 50000, category: "Trà sữa", img: "./btnhom-anh/tra-sua/tra-sua-o-long.jpg" },
    { id: 17, name: "Trà Sữa Thái Xanh", price: 40000, category: "Trà sữa", img: "./btnhom-anh/tra-sua/thai-xanh.jpg" },
    { id: 18, name: "Trà Sữa Socola", price: 40000, category: "Trà sữa", img: "./btnhom-anh/tra-sua/tra-sua-scl.jpg" },
    { id: 19, name: "Trà Chanh Dây", price: 45000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/chanh-day-xoai.jpg" },  
    { id: 20, name: "Hồng Trà Bí Đao", price: 40000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/hong-tra-bi-dao.jpg" },
    { id: 21, name: "Trà Atiso", price: 50000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-atiso.jpg" },
    { id: 22, name: "Trà Chanh Kiwi", price: 55000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-chanh-1.jpeg" },
    { id: 23, name: "Trà Chanh", price: 35000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-chanh-2.jpg" },
    { id: 24, name: "Trà Đào Xoài", price: 40000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-dao-xoai.jpg" },
    { id: 25, name: "Trà Chanh Dây", price: 35000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-chanh-day.jpg" },
    { id: 26, name: "Trà Đào ", price: 35000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-dao.jpg" },
    { id: 27, name: "Trà Hoa Cúc", price: 40000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-hoa-cuc.jpg" },
    { id: 28, name: "Trà Hoa Qué", price: 60000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-hoa-quế.jpg" },
    { id: 30, name: "Trà Mật Ong", price: 50000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-mat-ong.jpg" },
    { id: 31, name: "Trà Lài", price: 40000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-lai.jpg" },
    { id: 32, name: "Trà Quế ", price: 60000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-que.jpg" },
    { id: 33, name: "Trà Tắt", price: 30000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-tac.jpeg" },
    { id: 34, name: "Trà Vải Thiều", price: 55000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-vai-thieu.jpg" },
    { id: 35, name: "Trà Việt Quất", price: 55000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-viet-quat.jpg" },
    { id: 36, name: "Trà Xanh", price: 45000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-xanh.jpg" },
    { id: 37, name: "Trà Xoài", price: 45000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-xoai.jpg" },
    { id: 38, name: "Trà Dâu", price: 55000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-dau.jpg" },
    { id: 39, name: "Trà Cam Táo", price: 55000, category: "Trà", img: "./btnhom-anh/tra-trai-cay/tra-cam-tao.jpg" },
    { id: 40, name: "Trân Châu Đen", price: 5000, category: "Topping", img: "./btnhom-anh/topping/tran-chau-den.jpg" },
    { id: 41, name: "Thạch Trái Cây", price: 7000, category: "Topping", img: "./btnhom-anh/topping/thach-trai-cay-tra-cay.jpg" },
    { id: 42, name: "Kem Cheese", price: 10000, category: "Topping", img: "./btnhom-anh/topping/kem-chess.jpg" },
    { id: 43, name: "Bánh plan", price: 10000, category: "Topping", img: "./btnhom-anh/topping/banh-plan.jpg" },
    { id: 44, name: "Hạt Chia", price: 5000, category: "Topping", img: "./btnhom-anh/topping/hat-chia.jpg" },
    { id: 45, name: "Hạt Nổ Thủy Tinh", price: 10000, category: "Topping", img: "./btnhom-anh/topping/hat-no-thuy-tinh.jpg" },
    { id: 46, name: "Khúc Bạch Chân Mèo", price: 15000, category: "Topping", img: "./btnhom-anh/topping/khuc-bach-chan-meo.jpg" },
    { id: 47, name: "Khúc Bạch", price: 10000, category: "Topping", img: "./btnhom-anh/topping/khuc-bach.jpg" },
    { id: 48, name: "Thạch Dừa", price: 5000, category: "Topping", img: "./btnhom-anh/topping/thach-dua.jpg" },
    { id: 49, name: "Thạch Sương Sáo", price: 5000, category: "Topping", img: "./btnhom-anh/topping/thach-suong-sao.jpg" },
    { id: 50, name: "Trân Châu Hoàng Kim", price: 7000, category: "Topping", img: "./btnhom-anh/topping/tran-chau-hoang-kim.jpg" },
    { id: 51, name: "Trân Châu Khoai Môn", price: 7000, category: "Topping", img: "./btnhom-anh/topping/tran-chau-khoai-mon.jpg" },
    { id: 52, name: "Trân Châu Trắng", price: 7000, category: "Topping", img: "./btnhom-anh/topping/tran-chau-trang.jpg" },
];